### ISSUE TITLE
support AWS Session-Token in credentials

### ISSUE THREAD

**Issue by vincentkerdraon** [cycloidio/terracognita#154]
### Abstract
With AWS, we can provide `AccessKey`+	`SecretKey`
But I use SSO, and I also have a session token: environment var = `AWS_SESSION_TOKEN`.

### Proposal
Add an additional param for the token.

The error I get now: 
```
could not initialize 'reader' because: InvalidClientTokenId: The security token included in the request is invalid.
	status code: 403, request id: 12d27c61-9646-4c9f-86a6-bbfc51138204
```

Note: terraform does support the session token.

**Comment by tormath1** [comment]
Hi @vincentkerdraon ,

This error happens because we are passing an empty string as `token`:

https://github.com/cycloidio/terracognita/blob/649408d913c2a66a36250e91d8be11ba819b7fd1/aws/reader/connector.go#L127-L129


For AWS credentials loading, we use this:
https://github.com/cycloidio/terracognita/blob/649408d913c2a66a36250e91d8be11ba819b7fd1/cmd/aws.go#L130-L133

So we should be able to [fetch](https://github.com/aws/aws-sdk-go/blob/0d67c31d847a611f29e5870762e8bd751fc77f62/aws/credentials/env_provider.go#L63-L68) `AWS_SESSION_TOKEN` from the environment variables:
```go
	return Value{
		AccessKeyID:     id,
		SecretAccessKey: secret,
		SessionToken:    os.Getenv("AWS_SESSION_TOKEN"),
		ProviderName:    EnvProviderName,
	}, nil
```

We could also add a flag `--token` and pass the value like other credentials:

https://github.com/cycloidio/terracognita/blob/649408d913c2a66a36250e91d8be11ba819b7fd1/cmd/aws.go#L151-L153

Thanks for your feedback, would you be interested to do the implementation by yourself ? :relaxed:

**Comment by michaelakin** [comment]
I am getting this error with the latest docker container.  And I don't see any updates to this project in about 5 months.  Is it dead and abandoned?

docker pull cycloid/terracognita:v0.8.4   (latest)

**Comment by vincentkerdraon** [comment]
The fix for this issue is done since 2020. 
Maybe open a new issue if you find what's wrong.
