### ISSUE TITLE
Add connections between resources

### ISSUE THREAD

**Issue by xescugc** [cycloidio/terracognita#37]
Right now the HCL that we generate has the IDs of the resources it needs (security_group, security_group_rule, policy ...).

The idea would be to be able to use the resource attributes to reference between them `security_groups = ["${aws_security_group.elb-front.id}"]` this way would be more readable.

**Comment by tormath1** [comment]
I found this error while working on this issue: 

```
Error: could not import from google: error while Sync Config: error while fmt HCL: In <standard input>: At 19:13: Unknown token: 19:13 IDENT google_compute_network.HXShw.self_link
```

content to write should be in this format (TF12 compliant): 

```tf
...
network = google_compute_network.HXShw.self_link
...
```

We are using HCL through `github.com/hashicorp/hcl` (v1) but since TF12, we need to use `github.com/hashicorp/hcl/v2` (see https://github.com/hashicorp/terraform/commit/39e609d5fd708a3e2c63b347b2890e93b79e06af#diff-37aff102a57d3d7b797f152915a6dc16)

Only this file is impacted: https://github.com/cycloidio/terracognita/blob/df23fe2f8d2d162c99b9ae908a83ad2038c073cf/hcl/writer.go#L14-L16

**Comment by xescugc** [comment]
This is related to internally using the HCL that formats for TF 0.11 and it expects `${google_...}` as the value and as string.
