### ISSUE TITLE
resources not importable yet (example lb_listener_certificate)

### ISSUE THREAD

**Issue by talset** [cycloidio/terracognita#91]
**General information:**

Some resources like `lb_listener_certificate` are not importable via terraform (https://www.terraform.io/docs/providers/aws/r/lb_listener_certificate.html) but we are able to get the information needed to write the terraform files.

We should find a way to write it.

**Describe the bug:**

resource like `lb_listener_certificate` should be writable.

**Log message**

**Additional context**

**Comment by tormath1** [comment]
we could add a custom `SetImporter` function to the `Resource` interface

```go
SetImporter (*schema.ResourceImporter)
```

and set this importer while we create the resource. 

for, `lb_listener_certificate` it could be something like this:
```go
&schema.ResourceImporter{
        State: func(d *schema.ResourceData, meta interface{}) ([]*schema.ResourceData, error) {
                id := d.Id()
                sid := strings.Split(id, "_")
                d.Set("listener_arn", sid[0])
                d.Set("certificate_arn", sid[1])
                return []*schema.ResourceData{d}, nil
        },
}
```

it works pretty well and it doesn't bring breaking change.

**Comment by xescugc** [comment]
Also the question would be why is it not importable? They did not implement it on TF or it's just that it makes no sense? IDK just to know hehe.

**Comment by talset** [comment]
> Also the question would be why is it not importable? They did not implement it on TF or it's just that it makes no sense? IDK just to know hehe.

I would say for few resources like lb_listener_certificate can't be created alone in the aws console. it live within the aws_alb. So with the cli you never need to `terraform import`. So they didn't spend time on it (?).

But to define it with terraform it need to be a different resource.

**Comment by tormath1** [comment]
as @talset mentionned, lb_listener_certificate lives in a lb. since the `id` of this ressource is `{listener_arn}_{certificate_arn}` it won't be "user friendly" to import it in this way since you need to provide 2 ARNs. 
one other options could be to PR against components with missing importer to add a custom one. Like this one:
https://github.com/terraform-providers/terraform-provider-aws/blob/4d04815d5a1c63b8d9fa39c0a5cf194e8cd0c0a7/aws/resource_aws_kinesis_analytics_application.go#L25-L32
